language: ruby
rvm:
- 2.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Follows advice of https://github.com/jekyll/jekyll/issues/3480
install:
  - gem install jekyll
  - gem install html-proofer

script:
  - jekyll build
  - htmlproofer _site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - gh-pages-travis     # test the gh-pages-travis branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
