language: ruby
rvm:
- 2.1


# Follows advice of https://github.com/jekyll/jekyll/issues/3480
install:
  - gem install jekyll
  - gem install html-proofer

script:
  - jekyll build
  - htmlproofer _site
