# Site settings
title: MReportingPublic
email: wibeasley@hotmail.com
description: "Home Visiting Research in Oklahoma"
baseurl: /
url: "http://OuhscBbmc.github.io"
github_username: OuhscBbmc

# Build settings
markdown: kramdown
permalink: pretty

#Don't explode on gems; https://jekyllrb.com/docs/continuous-integration/#configuring-your-travis-builds.
exclude: [vendor]
